language: java
jdk:
  - openjdk8

#Travis를 어느 브랜치가 푸시될 때 수행할지 지정
branches:
  only:
    - master

#Travis 서버의 Home, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

before_deploy:
  - zip -r chacha *
  - mkdir -p deploy
  - mv chacha.zip deploy/chacha.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY   # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: chacha-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY   # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: chacha-build # S3 버킷
    key: chacha.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: chacha #  웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: chacha-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - tkdgusl94@gmail.com