server:
  port: 8080

spring:
  profiles:
    include: oauth, real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc

cloud:
  aws:
    s3:
      bucket: chacha-file
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

decorator:
  datasource:
    p6spy:
      enable-logging: false # p6spy 비활성화