server:
  port: 9090

database: hsqldb

spring:
  profiles:
    include: oauth, aws
  datasource:
  #    schema: classpath*:db/${database}/schema.sql
  #    data: classpath*:db/${database}/data.sql

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

cloud:
  aws:
    s3:
      bucket: chacha-file
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      springframework.web: debug

decorator:
  datasource:
    p6spy:
      enable-logging: false # p6spy 비활성화