server:
  port: 9000

database: hsqldb

spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql

  jpa:
    show_spl: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework.web: debug