server:
  port: 9000

spring:
  datasource:
    schema: classpath*:db/realdb/schema.sql
  profiles:
    include: oauth, real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc