create table if not EXISTS user (
  user_id bigint not null AUTO_INCREMENT,
  create_date timestamp,
  modified_date timestamp,
  email varchar(100) not null,
  name varchar(30) not null,
  picture varchar(255),
  role varchar(20),
primary key(user_id)
)engine = InnoDB;

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
 PRIMARY_ID CHAR(36) NOT NULL,
 SESSION_ID CHAR(36) NOT NULL,
 CREATION_TIME BIGINT NOT NULL,
 LAST_ACCESS_TIME BIGINT NOT NULL,
 MAX_INACTIVE_INTERVAL INT NOT NULL,
 EXPIRY_TIME BIGINT NOT NULL,
 PRINCIPAL_NAME VARCHAR(100),
CONSTRAINT SPRING_SESSION_PK PRIMARY KEY(PRIMARY_ID)
)engine = InnoDB;

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
 SESSION_PRIMARY_ID CHAR(36) NOT NULL,
 ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
 ATTRIBUTE_BYTES LONGBLOB NOT NULL,
 CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
 CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
)engine=InnoDB;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION(SESSION_ID);