CREATE TABLE IF NOT EXISTS user (
    id bigint generated by default as identity,
    create_date timestamp,
    modified_date timestamp,
    email varchar(255) not null,
    name varchar(255) not null,
    picture varchar(255),
    primary key (id)
)engine=InnoDB;

INSERT INTO user values (3, '2020-01-31 22:10:44.712903', '2020-01-31 22:10:44.712903', 'tkdgusl94@gmail.com', 'jeong', 'picture');

CREATE TABLE IF NOT EXISTS test (
    id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name varchar(255),
)engine=InnoDB;