CREATE TABLE IF NOT EXISTS user (
    id bigint generated by default as identity,
    create_date timestamp,
    modified_date timestamp,
    email varchar(255) not null,
    name varchar(255) not null,
    picture varchar(255),
    primary key (id)
)engine=InnoDB;

CREATE TABLE IF NOT EXISTS test{
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
}engine=InnoDB;